language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install: "pip install pep8 pylint"

script: "pep8 peevee tests && pylint peevee tests && nosetests"

notifications:
  email: false
